# ===============================
# = APPLICATION
# ===============================
server.port=8080
spring.threads.virtual.enabled=true
spring.application.name=proxy-meli
# ===============================
# = LOGGING
# ===============================
debug=${DEBUG:false}
logging.level.root=INFO
logging.level.com.ml.proxy=DEBUG
# ===============================
# = SWAGGER
# ===============================
springdoc.packagesToScan=com.ml.proxy
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.disable-swagger-default-url=true
# ===============================
# = ACTUATOR
# ===============================
management.endpoints.web.base-path=/manage
management.health.defaults.enabled=false
# ===============================
# = REDIS
# ===============================
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=
spring.redis.lua-script=local current current = redis.call('INCR', KEYS[1]) if current == 1 then redis.call('EXPIRE', KEYS[1], ARGV[1]) end if tonumber(current) > tonumber(ARGV[2]) then return 0 end return 1
# ===============================
# = MERCADO LIBRE CLIENT
# ===============================
mercado-libre.access-token=${ACCESS_TOKEN:duskbyhere}
mercado-libre.api-url=https://api.mercadolibre.com
mercado-libre.rate-limit.ip-max-requests=10
mercado-libre.rate-limit.path-max-requests=5
mercado-libre.rate-limit.comb-max-requests=3
mercado-libre.rate-limit.max-duration-seconds=60