# ===============================
# = APPLICATION
# ===============================
server.port=9999
spring.threads.virtual.enabled=true
spring.application.name=proxy-meli
# ===============================
# = LOGGING
# ===============================
logging.level.root=INFO
logging.level.com.ml.proxy=DEBUG
logging.level.org.apache.hc.client5.http=DEBUG
# ===============================
# = SWAGGER
# ===============================
springdoc.packagesToScan=com.ml.proxy
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.disable-swagger-default-url=true
# ===============================
# = ACTUATOR
# ===============================
management.endpoints.web.base-path=/manage
management.health.defaults.enabled=false
# ===============================
# = DATA SOURCE
# ===============================
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@claropay01atl.claro.amx:1521/ARDCPAY
spring.datasource.username=CPAYBFF
spring.datasource.password=Lunes8
spring.jpa.properties.hibernate.default_schema=CPAYBFF
# ===============================
# = Hikari configuration
# ===============================
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.auto-commit=false
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.max-lifetime=7200000
spring.datasource.hikari.minimum-idle=3
spring.datasource.hikari.connection-test-query=select 1 from dual
# ===============================
# = JPA / HIBERNATE
# ===============================
spring.jpa.show-sql=false
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=validate
# ===============================
# = REST CLIENT POOL CONFIG
# ===============================
rest-client.default.connect-timeout=30
rest-client.default.pool-deadline-timeout=5
rest-client.default.read-timeout=30
rest-client.default.max.total=400
rest-client.default.max-per-route=400
# ===============================
# = OTHER SERVICES CLIENT
# ===============================
user.url=https://ce446d4d-8626-4ace-968e-3ab298336eec.mock.pstmn.io
user.path=/example/{cellularNumber}
user.rest-client.max-per-route=400
user.rest-client.read-timeout=30
user.rest-client.connect-timeout=30
